"""
The Deal Outlet Tool Box — a single landing hub for Salman's internal
Flask tools (Internal - Catalogue and Operations Tool).

Deploy this exactly like the other tools (Flask + Render).
Set env vars:
  TDO_PIN        - shared PIN, used by any tool that doesn't set its own "pin"
  SECRET_KEY     - any random string, for session signing

To add a tool later: just add an entry to the TOOLS list below and redeploy.
To disable a tool without removing it: set "enabled": False.
To give a tool its own PIN instead of the shared one: set "pin": "1234".
Nothing else needs to change.
"""

import os
import time
from datetime import datetime, timezone

import requests
from flask import Flask, request, session, redirect, url_for, jsonify, render_template_string, abort

app = Flask(__name__)
app.secret_key = os.environ.get("SECRET_KEY", "dev-secret-change-me")

SHARED_PIN = os.environ.get("TDO_PIN", "9898")

LOGO_URL = "https://www.thedealoutlet.com/on/demandware.static/Sites-TheDealOutlet_AE-Site/-/default/dwf652137f/images/logo.svg"
BRAND_NAME = "The Deal Outlet Tool Box"
BRAND_EYEBROW = "Internal · Catalogue and Operations Tool"

# ---------------------------------------------------------------------------
# Tool registry — add new tools here.
#   id            - unique, used internally (routes, session keys, status)
#   enabled       - False hides it from the dashboard entirely
#   pin           - omit to use the shared TDO_PIN; set a string for a tool-specific PIN
#   health        - optional lightweight endpoint for the live status dot
# ---------------------------------------------------------------------------
TOOLS = [
    {
        "id": "scraper",
        "name": "The Deal - Product Details Scraper",
        "tag": "SCRAPER",
        "description": "Bulk-scrapes thedealoutlet.com for stock, price and image status across the full catalog. Uses Product ID from the SOH file as Input",
        "url": "https://thedealscraper.onrender.com",
        "health": "https://thedealscraper.onrender.com/health",
        "enabled": True,
        "pin": "1396",  # example: this one gets its own separate PIN
    },
    {
        "id": "category-monitor",
        "name": "Product Category Monitor",
        "tag": "MONITOR",
        "description": "Crawls live categories for data-quality issues — missing images, missing prices, broken listings. Uses live Category link as Input. No Product ID's needed",
        "url": "https://thedealcategorymonitor.onrender.com",
        "health": "https://thedealcategorymonitor.onrender.com/health",
        "enabled": True,
        "pin": "1396",  # example: this one gets its own separate PIN
    },
    {
        "id": "scanner",
        "name": "Product Barcode Scanner (Store Use)",
        "tag": "SCANNER",
        "description": "Barcode scan or OCR a physical item and match it to its website product code via the barcode map.",
        "url": "https://deal-product-scanner.onrender.com",
        "health": "https://deal-product-scanner.onrender.com/health",
        "enabled": True,
        "pin": "1396",  # example: this one gets its own separate PIN
    },
    {
        "id": "pricebook",
        "name": "Price Book Generator",
        "tag": "PRICE BOOK",
        "description": "Generates Price Book XML file for SFCC Import. Both UAE and KSA will work automatically.",
        "url": "https://sfcc-pricebook-tool-updated.onrender.com",
        "health": "https://sfcc-pricebook-tool-updated.onrender.com/health",
        "enabled": True,
        # no "pin" -> uses SHARED_PIN
    },
  {
        "id": "variation",
        "name": "Color & Size Variation Generator",
        "tag": "VARIATION",
        "description": "Generates the Color or Size or Both Variation required for SFCC Product Creation",
        "url": "https://deal-product-scanner.onrender.com",
        "health": "https://deal-product-scanner.onrender.com/health",
        "enabled": True,
        # no "pin" -> uses SHARED_PIN
    },
  {
        "id": "xmltoexcel",
        "name": "XML to Excel Convertor",
        "tag": "CONVERTOR",
        "description": "Converts the XML documents generated by SFCC to Excel Format",
        "url": "https://deal-product-scanner.onrender.com",
        "health": "https://deal-product-scanner.onrender.com/health",
        "enabled": True,
        # no "pin" -> uses SHARED_PIN
    },
]

# very small in-memory cache so the dashboard doesn't re-ping every tool
# on every page view
_status_cache = {}
CACHE_SECONDS = 45


def active_tools():
    return [t for t in TOOLS if t.get("enabled", True)]


def get_tool(tool_id):
    return next((t for t in active_tools() if t["id"] == tool_id), None)


def tool_pin(tool):
    return tool.get("pin") or SHARED_PIN


def check_health(tool):
    if not tool.get("health"):
        return "unknown"
    cached = _status_cache.get(tool["id"])
    if cached and (time.time() - cached["ts"]) < CACHE_SECONDS:
        return cached["status"]
    try:
        r = requests.get(tool["health"], timeout=4)
        status = "up" if r.status_code < 400 else "down"
    except requests.RequestException:
        status = "down"
    _status_cache[tool["id"]] = {"status": status, "ts": time.time()}
    return status


# ---------------------------------------------------------------------------
# Dashboard — open, no login wall. Each tool is gated individually below.
# ---------------------------------------------------------------------------
@app.route("/")
def dashboard():
    tools = active_tools()
    tags = sorted({t["tag"] for t in tools})
    return render_template_string(DASHBOARD_HTML, tools=tools, tags=tags,
                                   logo=LOGO_URL, brand=BRAND_NAME, eyebrow=BRAND_EYEBROW)


@app.route("/api/status")
def api_status():
    result = {t["id"]: check_health(t) for t in active_tools()}
    return jsonify({"status": result, "checked_at": datetime.now(timezone.utc).isoformat()})


# ---------------------------------------------------------------------------
# Per-tool PIN gate
# ---------------------------------------------------------------------------
@app.route("/unlock/<tool_id>", methods=["GET", "POST"])
def unlock(tool_id):
    tool = get_tool(tool_id)
    if not tool:
        abort(404)

    session_key = f"unlocked_{tool_id}"

    if request.method == "POST":
        if request.form.get("pin") == tool_pin(tool):
            session[session_key] = True
            return redirect(tool["url"])
        return render_template_string(UNLOCK_HTML, tool=tool, error="Wrong PIN.",
                                       logo=LOGO_URL, brand=BRAND_NAME, eyebrow=BRAND_EYEBROW)

    if session.get(session_key):
        return redirect(tool["url"])

    return render_template_string(UNLOCK_HTML, tool=tool, error=None,
                                   logo=LOGO_URL, brand=BRAND_NAME, eyebrow=BRAND_EYEBROW)


# ---------------------------------------------------------------------------
# Templates
# ---------------------------------------------------------------------------
UNLOCK_HTML = """
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{{ tool.name }} — {{ brand }}</title>
<link rel="icon" href="{{ logo }}">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link href="https://fonts.googleapis.com/css2?family=Fraunces:ital,wght@0,500;0,600;1,500&family=IBM+Plex+Mono:wght@400;500&display=swap" rel="stylesheet">
<style>
  :root{
    --bg:#14151A; --bg2:#0F1013; --panel:#1D1F26; --line:#2C2E37;
    --gold:#C9A66B; --gold-dim:#8E7A54; --ink:#F2EFE8; --dim:#B0B2BD; --err:#C4695F;
  }
  *{box-sizing:border-box;}
  body{
    margin:0; min-height:100vh; color:var(--ink); font-family:'IBM Plex Mono',monospace;
    display:flex; align-items:center; justify-content:center;
    background: radial-gradient(60% 50% at 50% 0%, rgba(201,166,107,.10), transparent 70%),
                linear-gradient(180deg, var(--bg) 0%, var(--bg2) 100%);
  }
  .card{
    width:min(380px,90vw); background:var(--panel); border:1px solid var(--line);
    border-radius:10px; padding:40px 36px; position:relative; overflow:hidden;
    box-shadow:0 30px 60px -20px rgba(0,0,0,.6); animation:rise .5s cubic-bezier(.2,.8,.2,1);
  }
  @keyframes rise{ from{opacity:0; transform:translateY(10px);} to{opacity:1; transform:translateY(0);} }
  .logo-wrap{ display:inline-flex; align-items:center; background:#fff; border-radius:8px; padding:8px 14px; margin:0 0 22px; }
  .logo{ display:block; height:22px; }
  h1{ font-family:'Fraunces',serif; font-weight:600; font-size:20px; margin:0 0 4px; }
  .eyebrow{ color:var(--gold); font-size:10.5px; letter-spacing:.14em; text-transform:uppercase; margin:0 0 26px; }
  input[type=password]{
    width:100%; padding:13px 14px; background:var(--bg); border:1px solid var(--line);
    color:var(--ink); border-radius:6px; font-family:inherit; font-size:15px;
    letter-spacing:.3em; margin-bottom:16px;
  }
  input[type=password]:focus{ outline:none; border-color:var(--gold); }
  button{
    width:100%; padding:13px; background:var(--gold); color:#181913; border:none;
    border-radius:6px; font-weight:500; letter-spacing:.06em; text-transform:uppercase;
    font-size:12.5px; cursor:pointer; font-family:inherit;
  }
  button:hover{ filter:brightness(1.1); }
  .err{ color:var(--err); font-size:12px; margin:-8px 0 14px; }
  a.back{ display:inline-block; margin-top:18px; color:var(--dim); font-size:12px; text-decoration:none; }
  a.back:hover{ color:var(--ink); }
</style>
</head>
<body>
  <form class="card" method="POST">
    <div class="logo-wrap"><img class="logo" src="{{ logo }}" alt="{{ brand }}"></div>
    <h1>{{ tool.name }}</h1>
    <p class="eyebrow">Enter PIN to continue</p>
    {% if error %}<p class="err">{{ error }}</p>{% endif %}
    <input type="password" name="pin" placeholder="PIN" autofocus>
    <button type="submit">Unlock</button>
    <a class="back" href="/">← Back to dashboard</a>
  </form>
</body>
</html>
"""

DASHBOARD_HTML = """
<!-- unchanged from your version, except each "Launch" link below -->
...
<a class="launch" href="{{ url_for('unlock', tool_id=t.id) }}" target="_blank" rel="noopener">Launch →</a>
...
"""

if __name__ == "__main__":
    app.run(debug=True, port=int(os.environ.get("PORT", 5000)))
